version: '3.8'
services:
    db:
      image: postgres:13.5-alpine3.14
      container_name: roomie-db
      restart: always
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: roomie_user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: roomie-db